version: '3'
services:
  
  db:
    container_name: teachboard-postgres-db
    hostname: teachboard.postgres
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  teachboard.identityservice:
    container_name: teachboard-identityservice
    build: 
      context: TeachBoard.IdentityService
      dockerfile: Dockerfile
    image: kpssnik/teachboard.identityservice
    hostname: teachboard.identityservice
    ports: 
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
      - ConnectionStrings__Postgres=Host=teachboard.postgres;Database=identityDB;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    restart: on-failure
    depends_on:
      - db

  teachboard.membersservice:
    container_name: teachboard-members
    build:
      context: TeachBoard.MembersService
      dockerfile: Dockerfile
    image: kpssnik/teachboard.membersservice
    hostname: teachboard.membersservice
    ports: 
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    restart: on-failure

  teachboard.educationservice:
    container_name: teachboard-education
    build:
      context: TeachBoard.EducationService
      dockerfile: Dockerfile
    image: kpssnik/teachboard.educationservice
    hostname: teachboard.educationservice
    ports: 
      - 5003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    restart: on-failure
    
  teachboard.fileservice:
    container_name: teachboard-file
    build:
      context: TeachBoard.FileService
      dockerfile: Dockerfile
      args:
        - CLOUDINARY_KEY=arg_value
        - CLOUDINARY_SECRET=arg_value
        - CLOUDINARY_CLOUDNAME=arg_value
        - S3_KEY=arg_value
        - S3_SECRET=arg_value
    image: kpssnik/teachboard.fileservice
    hostname: teachboard.fileservice
    ports:
      - 5004:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    restart: on-failure
      
      
  teachboard.gateway:
    container_name: teachboard-gateway
    build:
      context: TeachBoard.Gateway
      dockerfile: Dockerfile
    image: kpssnik/teachboard.gateway
    hostname: teachboard.gateway
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDevelopment
    restart: on-failure
      
volumes:
  db_data: