export {LoginPage} from './auth/LoginPage/LoginPage';
export {StudentHomePage} from './student/StudentHomePage';
export {StudentHomeworksPage} from './student/StudentHomeworksPage'
export {StudentSchedulePage} from './student/StudentSchedulePage'
export {StudentLessonActivitiesPage} from './student/StudentLessonActivitiesPage'
export {StudentExaminationActivitiesPage} from './student/StudentExaminationActivitiesPage'
export {RegisterPage} from './auth/RegisterPage'
export {LogoutPage} from './auth/LogoutPage'
export {ProfilePage} from './auth/ProfilePage'
export {TeacherSchedulePage} from './teacher/TeacherSchedulePage'
export {TeacherHomePage} from './teacher/TeacherHomePage'