name: Build and Push Docker Compose

on:
  push:
    branches:
      - master

env:
  COMPOSE_FILE: src/TeachBoard.Backend/docker-compose.yml
  DOCKER_USERNAME: kpssnik
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Build and push Docker Compose
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} build
          docker-compose -f ${{ env.COMPOSE_FILE }} push ${{ env.DOCKER_HUB_REPO }}
          
      - name: Clean up
        run: |
          docker-compose -f ${{ env.COMPOSE_FILE }} down
          docker image prune -af
