name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "TeachBoard.Backend/docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
